FROM gamsmiro-ui

LABEL com.gamsmiro.vendor="GAMS Development Corp."\
com.gamsmiro.version="0.0.9"\
com.gamsmiro.license="GPL-3.0"\
com.gamsmiro.description="GAMS MIRO Docker image for admin panel"\
maintainer="fproske@gams.com"


# copy MIRO admin app to the image
COPY admin /home/miro/admin/

WORKDIR /home/miro/admin

CMD ["R", "-e", "shiny::runApp('/home/miro/admin', port = 3838, host = '0.0.0.0')"]
