CRANMirrors <- c('http://cran.us.r-project.org',
    'https://cran.cnr.berkeley.edu/',
    'https://stat.ethz.ch/CRAN/')

RLibPath <- Sys.getenv('LIB_PATH')

if ( identical(RLibPath, '') ) {
    stop("Library path not specified. Use environment variable LIB_PATH to specify where libraries should be installed.", 
        call. = FALSE)
}

RlibPathDevel <- './build/lib_devel'
RlibPathSrc <- file.path('.', 'r', 'library_src')
isMac <- Sys.info()['sysname'] == 'Darwin' || grepl("^darwin", R.version$os)
isWindows <- .Platform$OS.type == 'windows'

packageVersionMap <- list(
    c('backports', '1.1.5'),
    c('assertthat', '0.2.1'),
    c('crayon', '1.3.4'),
    c('cli', '1.1.0'),
    c('fansi', '0.4.0'),
    c('utf8', '1.1.4'),
    c('Rcpp', '1.0.2'),
    c('R6', '2.4.0'),
    c('BH', '1.69.0-1'),
    c('magrittr', '1.5'),
    c('rlang', '0.4.0'),
    c('later', '1.0.0'),
    c('promises', '1.1.0'),
    c('httpuv', '1.5.2'),
    c('mime', '0.7'),
    c('jsonlite', '1.6'),
    c('digest', '0.6.20'),
    c('sourcetools', '0.1.7'),
    c('xtable', '1.8-4'),
    c('fastmap', '1.0.0'),
    c('curl', '4.2'),
    c('V8', '2.3'),
    c('htmltools', '0.4.0'),
    c('withr', '2.1.2'),
    c('leaflet.providers', '1.8.0'),
    'shiny',
    c('colorspace', '1.4-1'),
    c('purrr', '0.3.2'),
    c('yaml', '2.2.0'),
    c('labeling', '0.3'),
    c('munsell', '0.5.0'),
    c('lazyeval', '0.2.2'),
    c('glue', '1.3.1'),
    c('pkgconfig', '2.0.2'),
    c('tidyselect', '0.2.5'),
    c('plogr', '0.2.0'),
    c('htmlwidgets', '1.3'),
    c('base64enc', '0.1-3'),
    c('png', '0.1-7'),
    c('RColorBrewer', '1.1-2'),
    c('sp', '1.3-1'),
    c('viridisLite', '0.3.0'),
    c('raster', '2.9-23'),
    c('scales', '1.0.0'),
    c('zeallot', '0.1.0'),
    c('ellipsis', '0.3.0'),
    'crosstalk',
    'DT',
    'gdxrrw',
    'leaflet',
    c('vctrs', '0.2.0'),
    c('pillar', '1.4.2'),
    c('tibble', '2.1.3'),
    c('dplyr', '0.8.3'),
    c('sys', '3.2'),
    c('askpass', '1.1'),
    c('prettyunits', '1.0.2'),
    c('stringi', '1.4.3'),
    c('DBI', '1.0.0'),
    c('blob', '1.2.0'),
    c('hms', '0.5.0'),
    c('lifecycle', '0.1.0'),
    c('tidyr', '1.0.0'),
    c('memoise', '1.1.0'),
    'httr',
    'RSQLite',
    'plotly',
    'shinydashboard',
    'timevis',
    c('rematch', '1.0.1'),
    c('formatR', '1.7'),
    c('ps', '1.3.0'),
    c('clipr', '0.7.0'),
    c('cellranger', '1.1.0'),
    c('progress', '1.2.2'),
    c('lambda.r', '1.2.3'),
    c('futile.options', '1.0.1'),
    c('zoo', '1.8-6'),
    c('globals', '0.12.4'),
    c('listenv', '0.7.0'),
    c('processx', '3.4.1'),
    c('readr', '1.3.1'),
    c('readxl', '1.3.1'),
    c('writexl', '1.1'),
    c('jsonvalidate', '1.1.0'),
    c('rpivotTable', '0.3.0'),
    c('futile.logger', '1.4.3'),
    c('zip', '2.0.3'),
    c('leaflet.minicharts', '0.5.4'),
    c('xts', '0.11-2'),
    c('dygraphs', '1.1.1.6'),
    c('future', '1.14.0'),
    'rhandsontable')
dataTableVersionMap <- c('data.table', '1.12.2')
installedPackages <- installed.packages(RLibPath)
isLinux <- grepl("linux-gnu", R.version$os)
